stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

image: realgam3/aws-ecs-base:latest
services:
  - docker:dind
  
before_script:
  - docker context create ecs bsidestlv --from-env
  - aws ecr get-login-password | docker login --username "$AWS_ECR_REGISTRY_USER" --password-stdin $AWS_ECR_REGISTRY

build_image:
  stage: build
  script:
    - docker compose --file docker-compose.ecs.yml build
    - docker compose --file docker-compose.ecs.yml push

deploy_stack:
  stage: deploy
  script:
    - DOCKER_HOST=tcp://docker:2376 docker --context bsidestlv compose --file docker-compose.ecs.yml up -d