services:
  - docker:dind

default:
  image: realgam3/rancher-compose:latest
  tags:
    - docker

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

before_script:
  - rancher-convert -i $CI_REGISTRY_IMAGE
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker-compose -f docker-compose.build.yml build
    - docker-compose -f docker-compose.build.yml push

deploy_stack:
  stage: deploy
  script:
    - rancher-compose -f docker-compose.deploy.yml up --force-upgrade -c -d