image: realgam3/aws-ecs-base:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker context create ecs bsidestlv --from-env
  - echo $AWS_ECR_REGISTRY_PASSWORD | docker login -u "$AWS_ECR_REGISTRY_USER" --password-stdin $AWS_ECR_REGISTRY

build_image:
  stage: build
  script:
    - docker compose --file docker-compose.ecs.yml build
    - docker compose --file docker-compose.ecs.yml push

deploy_stack:
  stage: deploy
  script:
    - docker --context bsidestlv compose --file docker-compose.ecs.yml up -d