image: docker/compose:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
  - docker:dind

before_script:
  - docker info
#  - docker context create ecs bsidestlv --from-env
  - echo $AWS_ECR_REGISTRY_PASSWORD | docker login -u "$AWS_ECR_REGISTRY_USER" --password-stdin $AWS_ECR_REGISTRY

build_image:
  stage: build
  script:
    - docker compose -f docker-compose.ecs.yml build
    - docker compose -f docker-compose.ecs.yml push

#deploy_stack:
#  stage: deploy
#  script:
#    - docker --context bsidestlv compose -f docker-compose.ecs.yml up -d